runtime: python39  # Adjust the Python version as necessary
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT
env_variables:
  OPENAI_API_KEY: "sk-proj-DcyLBsh9VEJOO3FA0z8oT3BlbkFJ8fapY6I9kNlIyO3UNRWo"